### ISSUE TITLE
Publish the extension to VS Code

### ISSUE THREAD

**Issue by mikhailshilkov** [pulumi/pulumi-lsp#15]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

I would love to see the extension published in VS Code so that we wouldn't require manual installation. Publishing process is described here: https://code.visualstudio.com/api/working-with-extensions/publishing-extension

### Affected area/feature

Plugin installation

**Comment by iwahbe** [comment]
Waiting on conformation for launch on
- [X] Mac x86
- [X] Windows x86
- [ ] Mac M1

**Comment by iwahbe** [comment]
`v0.2.3` has been successfully published as a full release.
