### ISSUE TITLE
autocompleting resource type removes provider

### ISSUE THREAD

**Issue by foxydevloper** [pulumi/pulumi-lsp#77]
### What happened?

When pressing enter to autocomplete the resource type, it removes the provider's name, causing the code to error, and having to fix it manually.

https://user-images.githubusercontent.com/12120644/228966412-d566aa25-b6da-4e73-a713-aebea311d159.mp4

### Expected Behavior

Shouldn't remove provider name

### Steps to reproduce

press enter when resource type autocompletion appears

### Output of `pulumi about`

$ pulumi about
CLI
Version      3.60.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME          VERSION
digitalocean  unknown
yaml          unknown

Host
OS       Microsoft Windows 10 Pro for Workstations
Version  10.0.19044 Build 19044
Arch     x86_64

This project is written in yaml

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by foxydevloper** [comment]
Turns out this bug is caused by the Red Hat YAML extension, disabling it fixed the bug. So this is related to: #56

**Comment by ericrudder** [comment]
Thanks for the vid; will add this information to https://github.com/pulumi/pulumi-lsp/issues/56
